services:
  grafana:
    image: grafana/grafana:12.3.2
    container_name: dealeron-grafana
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3008:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-bigquery-datasource
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/fleet_overview.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - SA_CLIENT_EMAIL=${SA_CLIENT_EMAIL}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./secrets:/etc/grafana/secrets:ro
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
